# -*- coding: utf-8 -*-
"""AkaryakitTrafikLinearRegreesion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYzTZFcPV5_N6Q8hpQRxZUYXkeUkcIdA
"""

from google.colab import drive
drive.mount('/content/drive')

!pwd

import pandas as pd

"""**İlk Günlük araç sayısının versi On isleme**"""

#İlk Günlük araç sayısının Excel dosyası oku
file_path = "/content/drive/MyDrive/Data Analyts Project/2022-yl-gunluk-arac-saym (1).xlsx"
df = pd.read_excel(file_path)

#once bakalim
df.head()

#Sadece Sensor No 288 olan satirlari filtreleme yap ve gerekli sutunler secmek sonra sonucu goster
filtered_df = df[df["Sensor No"] == 288]
filtered_df = filtered_df[["Tarih", "Sensor No", "Sensor Adi", "ARAC TOPLAM"]]
filtered_df["Tarih"] = pd.to_datetime(filtered_df["Tarih"], dayfirst=True)
filtered_df = filtered_df.sort_values("Tarih", ascending=True)
filtered_df.head()

"""Temizlenmis veriyi yeni excel olarak kaydet klasorde"""

from google.colab import files

output_path = "/content/drive/MyDrive/Data Analyts Project/sensor_288_temizlenmis.xlsx"
filtered_df.to_excel(output_path, index=False)

output_path

"""**Ikinci veri seti Akaryakit On isleme**"""

file_path = "/content/drive/MyDrive/Data Analyts Project/akaryakit-fiyatlari-13.08.2025 03.27.40.xlsx"
df = pd.read_excel(file_path)
df.head()

filtered_df = df[["Tarih", "V/Max Kurşunsuz 95"]]
filtered_df["Tarih"] = pd.to_datetime(filtered_df["Tarih"], dayfirst=True)
filtered_df = filtered_df.sort_values("Tarih", ascending=True)
filtered_df.head()

from google.colab import files

output_path = "/content/drive/MyDrive/Data Analyts Project/Akaryakit_temizlenmis1.xlsx"
filtered_df.to_excel(output_path, index=False)

output_path

"""**Tarih üzerinden iki veriyi birleştirmek ve Akayakıt fiyat ve Araç Linear regression**

"""

import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# veriler yukle
file_path = "/content/drive/MyDrive/Data Analyts Project/sensor_288_temizlenmis.xlsx"
trafik_df = pd.read_excel(file_path)
file_path ="/content/drive/MyDrive/Data Analyts Project/Akaryakit_temizlenmis1.xlsx"
yakit_df = pd.read_excel(file_path)

# Tarih sutunleri datetime formatina cevir cunku 2 dosyada tarihler farkli tipi oldugu icin
trafik_df["Tarih"] = pd.to_datetime(trafik_df["Tarih"])
yakit_df["Tarih"] = pd.to_datetime(yakit_df["Tarih"])
# birleştirme yap
df = pd.merge(trafik_df, yakit_df, on="Tarih")

# V/Max Kurşunsuz 95 sadece sayısal al
df["V/Max Kurşunsuz 95"] = df["V/Max Kurşunsuz 95"].astype(str).str.replace(" TL/LT", "")
df["V/Max Kurşunsuz 95"] = df["V/Max Kurşunsuz 95"].astype(float)

# Extract features (X) and target (y) after cleaning
X = df[["V/Max Kurşunsuz 95"]]
y = df["ARAC TOPLAM"]

model = LinearRegression()
model.fit(X, y)

y_pred = model.predict(X)

print("Eğim (slope):", model.coef_[0])
print("Y-kesişim (intercept):", model.intercept_)
print("R-kare (R²) değeri:", model.score(X, y))

plt.scatter(X, y, color="green", label="Gerçek Veriler")
plt.plot(X, y_pred, color="red", label="Regresyon Çizgisi")
plt.xlabel("V/Max Kurşunsuz 95 (Akaryakıt Fiyatı TL/LT)")
plt.ylabel("Araç Toplamı (Trafik)")
plt.title("Akaryakıt Fiyatı - Trafik İlişkisi")
plt.legend()
plt.show()